import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
    },
    headerButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        minWidth: 80,
        alignItems: 'center',
    },
    postButton: {
        paddingHorizontal: 20,
    },
    headerButtonText: {
        fontSize: 16,
        fontWeight: '600',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    headerTitleContainer: {
        alignItems: 'center',
        flex: 1,
    },
    headerSubtitle: {
        fontSize: 13,
        fontWeight: '500',
        marginTop: 2,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    userRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    username: {
        fontSize: 16,
        fontWeight: '600',
    },
    textInput: {
        fontSize: 18,
        lineHeight: 24,
        minHeight: 120,
        padding: 16,
        borderWidth: 1,
        borderRadius: 12,
        marginBottom: 8,
    },
    charCountRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 16,
    },
    charCount: {
        fontSize: 14,
    },
    imagesContainer: {
        marginBottom: 16,
    },
    imagesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    imagesCount: {
        fontSize: 14,
        fontWeight: '600',
    },
    clearAllButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
    },
    clearAllText: {
        fontSize: 12,
        fontWeight: '500',
    },
    imagesScrollView: {
        marginHorizontal: -8,
    },
    imagesScrollContent: {
        paddingHorizontal: 8,
    },
    imageContainer: {
        position: 'relative',
        marginRight: 8,
        width: 120,
    },
    imagePreview: {
        width: 120,
        height: 120,
        borderRadius: 8,
        backgroundColor: '#f0f0f0',
    },
    removeImageButton: {
        position: 'absolute',
        top: 4,
        right: 4,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: 16,
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actions: {
        flexDirection: 'column',
        marginBottom: 16,
    },
    markdownToolbar: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        gap: 8,
    },
    markdownButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    mediaButtons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    mediaButtonWrapper: {
        alignItems: 'center',
    },
    actionButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        position: 'relative',
    },
    imageBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        borderRadius: 10,
        width: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    imageBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    gifBadge: {
        position: 'absolute',
        bottom: 4,
        right: 4,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 3,
    },
    gifBadgeText: {
        color: '#fff',
        fontSize: 8,
        fontWeight: 'bold',
    },
    buttonLabel: {
        fontSize: 11,
        marginTop: 4,
        fontWeight: '500',
    },
    limitText: {
        fontSize: 12,
        marginTop: 8,
        marginLeft: 8,
    },
    hintText: {
        fontSize: 12,
        marginTop: 8,
        marginLeft: 8,
        fontStyle: 'italic',
    },
    sharedIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    sharedText: {
        marginLeft: 8,
        fontSize: 14,
        fontStyle: 'italic',
    },
    notificationStatus: {
        marginTop: 8,
        padding: 8,
        borderRadius: 6,
        backgroundColor: 'rgba(0,0,0,0.05)',
    },
    // Spoiler modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    spoilerModal: {
        width: '85%',
        borderRadius: 16,
        padding: 24,
        borderWidth: 1,
    },
    spoilerModalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 8,
        textAlign: 'center',
    },
    spoilerModalDescription: {
        fontSize: 14,
        marginBottom: 16,
        textAlign: 'center',
        lineHeight: 20,
    },
    spoilerInput: {
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        marginBottom: 20,
    },
    spoilerModalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    spoilerModalButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    spoilerModalButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
});
